### ISSUE TITLE
Bug Report: Game crashes when trying to change offset of char in character editor

### ISSUE THREAD

**Issue by magicmanreal1** [CodenameCrew/CodenameEngine#668]
![Image](https://github.com/user-attachments/assets/9fb550e6-1999-4798-87de-c4238a508dd0)

[weed]: <> (MAKE SURE THAT THE ISSUE IS AS COMPLETE AS POSSIBLE. ISSUES THAT HAVE BARELY ANY INFORMATION OR IS ONLY MADE FOR TROLLING WILL BE INSTANTLY CLOSED.)
[weed]: <> (MAKE SURE TO ADD YOUR TARGET OR IT'LL BE IGNORED!)

### Which target are you using?
[weed]: <> (CHANGE [ ] TO [x] IN FRONT OF YOUR TARGET!)

[x] Windows
[ ] Linux
[ ] Mac

### Explain your issue
so im tryna make a character for my mod but when i try change the offset it crashed
##### Please check first if your issue haven't already been reported yet.
it has but its nothing to do with it being a psych engine [character](url)
[weed]: <> (MAKE SURE TO ADD A SCREENSHOT OF THE CRASH HANDLER, IF AVAILABLE, AND STEPS TO REPRODUCE THE BUG!)

**Comment by kitzsh** [comment]
i think i've had this bug before
for now you might be able to work around it by saving, exiting and going back into the character editor after changing the spritesheet
i'll look into the code and see if there's a proper fix

**Comment by magicmanreal1** [comment]
fixed it

**Comment by ACoolioDude** [comment]
> fixed it

Close the issue if you solved it

**Comment by kitzsh** [comment]
> > fixed it
> 
> Close the issue if you solved it

I'm assuming by "fixed" he means he was able to get the offsets working, but it still crashes under a certain condition (changing the spritesheet and then the offsets without reloading the editor) and that still needs to be fixed

**Comment by ACoolioDude** [comment]
> > > fixed it
> > 
> > 
> > Close the issue if you solved it
> 
> I'm assuming by "fixed" he means he was able to get the offsets working, but it still crashes under a certain condition (changing the spritesheet and then the offsets without reloading the editor) and that still needs to be fixed

Ah, mb
